name: wflow

channels:
  - conda-forge
  - defaults

dependencies:
  # required
  - pcraster>=4.3
  - numpy>=1.12
  - scipy>=1.0
  - gdal>=3
  - netcdf4>=1.4.1
  - xarray>=0.11
  - cftime>=1.0.4
  - numba>=0.48
  - pyproj>=2.4
  - python-dateutil>=2.7
  # optional
  - thrift>=0.11
  - pyinstaller>=3.3
  - setuptools_scm
  - setuptools>=38
  - pip>=9.0.3
  - black
  - pylint
  - sphinx
  - sphinx_rtd_theme
  - matplotlib
  - pip:
    - bmi-python
